title: Desarrollo con React
description: El curso en línea "Introducción al Desarrollo Frontend con React".
theme: just-the-docs

url: https://patroneshermosos-oficial.github.io/intro-react

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/patroneshermosos-oficial/intro-react

